In [3]:
#Import the needed packages:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [4]:
# load the iris dataset

iris_data = load_iris() 
# a simple print 

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


In [5]:
# Convert data to a single column
x = iris_data.data
y_ = iris_data.target.reshape(-1, 1)

In [6]:
# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)

In [7]:
# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

In [8]:
# Build the model

model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
print('Neural Network Model Summary: ')
print(model.summary())

Neural Network Model Summary: 
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 fc1 (Dense)                 (None, 10)                50        
                                                                 
 fc2 (Dense)                 (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [9]:
# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=1000)

Epoch 1/1000
24/24 - 0s - loss: 0.9983 - accuracy: 0.3750 - 458ms/epoch - 19ms/step
Epoch 2/1000
24/24 - 0s - loss: 0.9746 - accuracy: 0.4667 - 39ms/epoch - 2ms/step
Epoch 3/1000
24/24 - 0s - loss: 0.9531 - accuracy: 0.5833 - 37ms/epoch - 2ms/step
Epoch 4/1000
24/24 - 0s - loss: 0.9335 - accuracy: 0.5917 - 37ms/epoch - 2ms/step
Epoch 5/1000
24/24 - 0s - loss: 0.9156 - accuracy: 0.6583 - 36ms/epoch - 2ms/step
Epoch 6/1000
24/24 - 0s - loss: 0.8975 - accuracy: 0.6500 - 39ms/epoch - 2ms/step
Epoch 7/1000
24/24 - 0s - loss: 0.8810 - accuracy: 0.7000 - 39ms/epoch - 2ms/step
Epoch 8/1000
24/24 - 0s - loss: 0.8651 - accuracy: 0.6667 - 36ms/epoch - 1ms/step
Epoch 9/1000
24/24 - 0s - loss: 0.8511 - accuracy: 0.6250 - 36ms/epoch - 1ms/step
Epoch 10/1000
24/24 - 0s - loss: 0.8375 - accuracy: 0.6250 - 48ms/epoch - 2ms/step
Epoch 11/1000
24/24 - 0s - loss: 0.8254 - accuracy: 0.6333 - 35ms/epoch - 1ms/step
Epoch 12/1000
24/24 - 0s - loss: 0.8131 - accuracy: 0.6333 - 36ms/epoch - 2ms/step
Epoch 13/10

In [10]:
# Test on unseen data
results = model.evaluate(test_x, test_y)


1/1 [==============================] - 0s 140ms/step - loss: 0.0474 - accuracy: 0.9667


In [11]:
#Print the loss&accuracy value
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Final test set loss: 0.047379
Final test set accuracy: 0.966667
